name: challenges
channels:
  - pytorch
  - nvidia
  - conda-forge
  - defaults
dependencies:
  - python=3.11
  - pip
  - numpy
  - scipy
  - pandas
  - pillow
  - scikit-learn
  - pyyaml
  - python-dotenv
  - pyarrow
  - cffi
  - jpeg
  - pytest
  - ruff
  - tensorboard
  - pip:
      - albumentations
      - opencv-python-headless
      - timm
      - torch
      - torchvision
