extends: baseline_mixed_original.yaml
paths:
  run_name: efficientvit_b2_1024_mixed_original
model:
  encoder_name: efficientvit_b2.r288_in1k
dataset:
  image_size: 1024
train:
  batch_size: 2
  accum_steps: 8
