extends: baseline_mixed_original.yaml
paths:
  run_name: pvt_v2_b2_emcad_mixed_original
model:
  decoder_name: emcad
  decoder_kwargs:
    kernel_sizes:
    - 1
    - 3
    - 5
    expansion_factor: 2
    lgag_kernel_size: 3
    activation: relu
train:
  resume: false
